---
- name: Insall Homebrew + required packages
  ansible.builtin.include_role:
    name: geerlingguy.mac.homebrew
  vars:
    # This is overwritten by our group_vars (cpp.build-machines)
    homebrew_installed_packages:
      - "{{ required_packages }}"
  when: not cpp_buildmachine

- name: "{{ proget_downloads_directory }}: Ensure download directory is present"
  ansible.builtin.file:
    path: "{{ proget_downloads_directory }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: "0755"
  become: true

- name: Ensure proget status archives directory is present
  ansible.builtin.file:
    path: "{{ proget_status_directory }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: "0755"
  become: true

- name: Setup PGutil MacOS
  block:
    - name: Download PGutil {{ pgutil_version }}
      ansible.builtin.get_url:
        url: "{{ pgutil }}"
        dest: "/tmp/pgutil-osx-arm64.zip"
        mode: "0640"
        force: yes

    - name: Extract pgutil
      ansible.builtin.unarchive:
        src: "/tmp/pgutil-osx-arm64.zip"
        dest: "{{ pg_dest }}"
        remote_src: true
        mode: "0755"
      become: true

- name: Ad-hoc sign pgutil so Gatekeeper allows it
  become: true
  ansible.builtin.command: /usr/bin/codesign --force --sign - {{ pg_dest }}/pgutil

- name: Verify spctl sees a signature (non-fatal check)
  ansible.builtin.command: /usr/sbin/spctl -a -vv {{ pg_dest }}/pgutil
  register: spctl_check
  changed_when: false
  failed_when: false

- debug:
    var: spctl_check.stdout_lines

- name: Add PGutil source
  ansible.builtin.command: >
    pgutil sources add
    --name={{ pgutil_source_name }}
    --url={{ proget_base_url }}
    --api-key={{ ansible_deployment_proget_key }}
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"

- name: Get and expand archives
  ansible.builtin.include_tasks: expand_archive_posix.yml
  loop: "{{ archive_definitions }}"
  loop_control:
    loop_var: archive
