---
- name: Insall Homebrew + required packages
  ansible.builtin.include_role:
    name: geerlingguy.mac.homebrew
  vars:
    # This is overwritten by our group_vars (cpp.build-machines)
    homebrew_installed_packages:
      - "{{ required_packages }}"
  when: not cpp_buildmachine

- name: "{{ proget_downloads_directory }}: Ensure download directory is present"
  ansible.builtin.file:
    path: "{{ proget_downloads_directory }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: "0755"
  become: true

- name: Ensure proget status archives directory is present
  ansible.builtin.file:
    path: "{{ proget_status_directory }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: "0755"
  become: true

- name: Add CCDC Homebrew tap
  community.general.homebrew_tap:
    name: ccdc-opensource/homebrew-packages
    state: present

- name: Install pgutils via Homebrew
  community.general.homebrew_cask:
    name: ccdc-opensource/packages/pgutils
    state: present

- name: Find pgutil binary location
  ansible.builtin.shell: which pgutil || find /usr/local /opt/homebrew /Applications -name pgutil -type f 2>/dev/null | head -1
  register: pgutil_path
  environment:
    PATH: "/opt/homebrew/bin:/usr/local/bin:{{ ansible_env.PATH }}"
  changed_when: false

- name: sign pgutil so Gatekeeper allows it
  become: true
  ansible.builtin.command: /usr/bin/codesign --force --sign - "{{ pgutil_path.stdout }}"
  when: pgutil_path.stdout | length > 0

- name: Verify spctl sees a signature on pgutil
  ansible.builtin.command: /usr/sbin/spctl -a -vv "{{ pgutil_path.stdout }}"
  register: spctl_check
  changed_when: false
  failed_when: false
  when: pgutil_path.stdout | length > 0

- name: Debug spctl output
  debug:
    var: spctl_check.stdout_lines
  when: spctl_check is defined

- name: Add PGutil source
  ansible.builtin.command: "{{ pgutil_path.stdout }} sources add --name={{ pgutil_source_name }} --url={{ proget_base_url }} --api-key={{ ansible_deployment_proget_key }}"
  environment:
    PATH: "/opt/homebrew/bin:/usr/local/bin:{{ ansible_env.PATH }}"

- name: Get and expand archives
  ansible.builtin.include_tasks: expand_archive_posix.yml
  loop: "{{ archive_definitions }}"
  loop_control:
    loop_var: archive
