---
- name: Ensure proget status archives directory is present
  ansible.windows.win_file:
    path: "{{ proget_status_directory }}"
    state: directory

- name: Ensure proget downloads archives directory is present
  ansible.windows.win_file:
    path: "{{ proget_downloads_directory }}"
    state: directory

- name: Ensure proget tempdownloads archives directory is present
  ansible.windows.win_file:
    path: "{{ proget_tempdownloads_directory }}"
    state: directory

- name: Install required tools
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ required_packages }}"
  become: true

- name: Add PGutil source
  ansible.windows.win_shell: pgutil sources add --name={{ pgutil_source_name }} --url={{ proget_base_url }} --api-key={{ ansible_deployment_proget_key }}

- name: Get and expand archives
  ansible.builtin.include_tasks: expand_archive_windows.yml
  loop: "{{ archive_definitions }}"
  loop_control:
    loop_var: archive
